name: Publish Vuepress

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install and Build
      env:
        NODE_OPTIONS: --openssl-legacy-provider
        BASE: ${{ vars.BASE }}
      run: |
        yarn install
        yarn build

    - name: Publish gh-pages
      env:
        REPO: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd .vuepress/dist
        echo "guide.v2fly.org" > CNAME
        git init --initial-branch=gh-pages .
        git config user.name V2FlyContrib
        git config user.email SharedAccount+V2FlyContrib@unial.org
        git config commit.gpgsign false
        git add -A
        git commit -m "GitHub Actions @ $(date -u -Ins)"
        git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git
        git push -f -v --progress origin gh-pages:gh-pages
